apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nano-banana-pro-cli
  name: nano-banana-pro-cli
  namespace: acedatacloud
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: nano-banana-pro-cli
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nano-banana-pro-cli
    spec:
      containers:
        - name: nano-banana-pro-cli
          image: ghcr.io/acedatacloud/nano-banana-pro-cli:${TAG}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
